# Generated by Django 5.2.4 on 2025-08-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODABSApp', '0002_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='days',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
