# Generated by Django 5.2.4 on 2025-08-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ODABSApp', '0003_doctoravailability_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='date',
            new_name='time_from',
        ),
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='time',
            new_name='time_to',
        ),
    ]
