# Generated by Django 5.2.4 on 2025-08-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODABSApp', '0005_patientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=20)),
                ('time', models.CharField(blank=True, max_length=10)),
                ('message_or_reason', models.TextField(blank=True, max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ODABSApp.patientprofile')),
            ],
        ),
    ]
