# Generated by Django 5.2.4 on 2025-08-05 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODABSApp', '0006_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ODABSApp.doctorprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='next_app',
            field=models.BooleanField(default=True),
        ),
    ]
