# Generated by Django 5.2.4 on 2025-08-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODABSApp', '0007_appointments_doctor_appointments_next_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ODABSApp.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ODABSApp.patientprofile')),
            ],
        ),
    ]
