# Generated by Django 5.2.4 on 2025-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODABSApp', '0008_medicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
