# Generated by Django 5.2.4 on 2025-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODABSApp', '0009_alter_medicalhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
