# Generated by Django 5.2.4 on 2025-08-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODABSApp', '0010_medicalhistory_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='next_app',
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default='Pending'),
        ),
    ]
