# Generated by Django 5.2.4 on 2025-08-06 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODABSApp', '0011_remove_appointments_next_app_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ODABSApp.appointments'),
            preserve_default=False,
        ),
    ]
